# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test01:
    cmds:
      - poetry run uvicorn test01:app --port 8001
    silent: true

  test02:
    cmds:
      - poetry run uvicorn test02:app --port 8001
    silent: true

  test03:
    cmds:
      - poetry run uvicorn test03:app --port 8001
    silent: true

  test04:
    cmds:
      - poetry run uvicorn test04:app --port 8001
    silent: true

  test05:
    cmds:
      - poetry run uvicorn test05:app --port 8001
    silent: true

  test06:
    cmds:
      - poetry run uvicorn test06:app --port 8001

  test07:
    cmds:
      - poetry run uvicorn test07:app --port 8001
